name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm test

      - run: sudo apt-get install -y librsvg2-bin

      - run: npm run build

      - run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - run: echo "VERSION=$(jq -r .version manifest.json)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: tab-zap-${{ env.VERSION }}-${{ env.SHORT_SHA }}
          path: |
            manifest.json
            icons/icon16.png
            icons/icon48.png
            icons/icon128.png
            popup/popup.html
            popup/popup.css
            popup/popup.bundle.js
            background/background.bundle.js
