name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm test

      - run: sudo apt-get install -y librsvg2-bin

      - run: npm run package

      - run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - run: mv tab-zap.zip tab-zap-${{ env.SHORT_SHA }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: tab-zap-${{ env.SHORT_SHA }}
          path: tab-zap-${{ env.SHORT_SHA }}.zip
