name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm test

      - run: sudo apt-get install -y librsvg2-bin

      - run: npm run package

      - run: mv tab-zap.zip tab-zap-${{ github.sha }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: tab-zap-${{ github.sha }}
          path: tab-zap-${{ github.sha }}.zip
